replicaCount: 1
image:
  repository: tensorchord/envd-server
  pullPolicy: Always
  tag: ''
dbUrl: ''
server:
  debug: false
  noauth: true
  imagePullSecret: ''
  migration: true
  migrationImage: ''
containersshimage:
  repository: tensorchord/containerssh
  pullPolicy: IfNotPresent
  tag: 0.0.6
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
postgres:
  createdb: true
  tag: '11.7'
  dbname: postgresdb
  username: postgresadmin
  password: admin12345
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  serverPort: 8080
  containersshPort: 2222
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
